### ISSUE TITLE
style 부분은 각각의 css로 빼주세요.

### ISSUE THREAD

**Issue by Ysungjae** [KIM-KYOUNG-OH/Assignment_1#1]
html과 동일한 파일명으로 css를 생성해주세요 (ex. index.html  & index.css)

html로 linkrel를 사용하여 css를 적용해주세요.

css는 css라는 하나의 폴더에 모아두는 것이 좋습니다.

**Comment by KIM-KYOUNG-OH** [comment]
수정완료
