### ISSUE TITLE
style 오류 수정

### ISSUE THREAD

**Issue by Ysungjae** [KIM-KYOUNG-OH/Assignment_1#2]
aboutme.html의 38번째 줄

    <div style="background-color: green; width: 1000px; height: 680px;" margin-top:5px;>

margin-top이 style 밖으로 나가있어 오류가있습니다.

또한 html안에 style 코드 삽입을 자제하고 css로 빼주세요.

**Comment by KIM-KYOUNG-OH** [comment]
수정완료
