### ISSUE TITLE
모든 이미지, 링크는 상대경로로 수정해주세요.

### ISSUE THREAD

**Issue by Ysungjae** [KIM-KYOUNG-OH/Assignment_1#3]
현재 코드의 링크는 아래와 같이 모두 절대 경로로 되어있습니다.
a href="C:\ToyProject\assignment\photo.html"

절대경로를 상대경로로 수정해주세요.
상대경로란
./     : 현재 위치
../    : 현재위치의 상위 입니다.
자세한 내용은 구글 검색을 활용해주세요.

즉 위 코드는 아래와 같이 수정되어야합니다.
a href="./photo.html"

**Comment by KIM-KYOUNG-OH** [comment]
수정완료
